### PR TITLE
adding first basic collision system, with a very slow gravity

### PR DESCRIPTION
**Pull request by SuperFola**
Resolves: #43 
Authors:
@SuperFola 

## Summary of changes
- adding a `setWorld` (temporary, but since it's the camera who's handling the movement atm) to the camera
- updating the camera.tick function to add collision detection and gravity (very basic, should be updated in the future)
  
## Caveats
Does this introduce any new bugs?
- falling into the void if the player spawns with no block below them
- falling while flying

## On approval
Wait for me for confirmation.

### CODE REVIEW

**Comment by beeperdeeper089** [comment]
I personally think rather than hacking this in, we should probably implement the movement system (remember that we're going to try use an ECS design) and have that do it. This will make the eventual integration of the server less painful and will reduce the coupling of our code at this point in time.

If we keep this (it's fine for now if we decide it's not worth the effort), we NEED to implement a flying mode otherwise if we're testing something and we accidently fall off the world then we just fall forever, and we also need to change the spawn position from 0, 0, 0 to the top or something where we don't just fall and die to start with.

**Comment by tobyplowy** [comment]
I have been testing this with tears of joy in my eyes. 
This is amazing! Thanks Fola. 

Now for some of the issues I found while testing:
•While holding shift and standing on the ground the camera sinks underground? 
•You can walk into walls.
•The camera should be 2 blocks tall instead of the current 1 block tall. 
And the above stated by Vyom.

**Comment by tobyplowy** [comment]
@SuperFola Can you fix the conflicts and add wall collision so this PR can be merged?

**Comment by beeperdeeper089** [comment]
@SuperFola if we get the conflicts resolved on here, i'll get this reviewed asap and we can try to get this stuff in.

**Comment by tobyplowy** [comment]
Closing due to inactivity. Please feel free to request a reopening if you do decide to continue work.

**Pull request closed without merging**
