### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by beeperdeeper089**
why did we have it like this

### CODE REVIEW

**Comment by apachano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 4
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GentenStudios/Phoenix/pullRequest?prid=4779183&bid=15921749)

**Comment by apachano** [comment]
Looks like it was added in 3.13? https://cmake.org/cmake/help/v3.13/manual/cmake.1.html
@beeperdeeper089

**Comment by beeperdeeper089** [comment]
Yeah I noticed that (i think i mentioned it on discord too) but TravisCI only has 3.12 which sucks :(

**Comment by beeperdeeper089** [comment]
But I guess we can keep using the ``-H`` argument on Travis and just make people use the newer version, but if we set the minimum required, then it won't work on Travis unless we set it depending on the build environment - which i think is really hacky and we shouldn't do that.

**Comment by beeperdeeper089** [comment]
Let's put this PR on hold for a bit until we figure out if we can get a better version of CMake on CI.

**Pull request closed without merging**
