### PR TITLE
Make logger actually output to a file.

### PR DESCRIPTION
**Pull request by beeperdeeper089**
Resolves: #
Authors:
@beeperdeeper089 

## Summary of changes
- Make logger output to file
- Get rid of cmake auto-updating submodules, since it slows down VS builds and was actually making my builds fail.
  
## Caveats
Does this introduce any new bugs?
- None

## On approval
Merge.

### CODE REVIEW

**Comment by beeperdeeper089** [comment]
I'm stupid, I've actually just forgotten to output to a file in the actual logging method.

**Comment by tobyplowy** [comment]
Good thing I'm testing PRs right ;D

**Comment by beeperdeeper089** [comment]
should be fixed now @tobyplowy

**Comment by tobyplowy** [comment]
Works! cool.

**Review by apachano — APPROVED** [review]

**Pull request merged**
