### PR TITLE
Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by beeperdeeper089**

### CODE REVIEW

**Comment by M3TIOR** [comment]
@beeperdeeper089 Is it possible that you could expain a little better in your commit messages why you need to do what looks like 10 redundant commits?

**Comment by beeperdeeper089** [comment]
Idek what I'm doing myself, I'm gonna have to squash and merge this anyway so it's only one commit

**Comment by M3TIOR** [comment]
I just thought it could be nice to be able to learn from your mistakes as well as my own. That way whatever you're getting wrong is more preventable in the future.

**Comment by apachano** [comment]
@beeperdeeper089 Besides the mess where other branches got merged in, this looks good. My only question is what is the latest version of OSX it supports?

**Comment by beeperdeeper089** [comment]
Mojave 10.14 if that means anything to you

https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops

**Comment by apachano** [comment]
It wont compile filesystem :/ and depending on the xtools version it will still set all the flags to true so we cant detect that it cant until it throws a custom error.

**Comment by apachano** [comment]
Same as Travis

**Comment by beeperdeeper089** [comment]
We could maybe install a custom version of clang?

What we could do is build CLang for macOS and store it in the Azure Artifacts and use that build to compile? That's long and winded so preferably not but yeah, we need to figure out something for Crapple.

**Pull request closed without merging**
