### PR TITLE
Feat inventory stacks

### PR DESCRIPTION
**Pull request by apachano**
Resolves: #325 
Authors:
@apachano 

## Summary of changes
- Implement ability to stack items in inventory
- Allow specifying a max stack size during block registration
  
## Caveats
- Due to lack of support from ImGui, the intractability is limited (no right click)

## On approval
Merge

### CODE REVIEW

**Comment by tobyplowy** [comment]
Don't build for me.

**Comment by JosiahWI** [comment]
Do you have a build/compilation log?

**Review by beeperdeeper089 — APPROVED** [review]
LGTM, my awful QA standards aren't complaining - @tobyplowy have you tested this?

**Comment by apachano** [comment]
Apparently the review persists through merge conflict resolution lol. @tobyplowy do we have a +1 from you? If so feel free to hit the button.

**Comment by tobyplowy** [comment]
Builds and runs, Good job!

**Pull request merged**
