### PR TITLE
Fix Window Scaling issue.

### PR DESCRIPTION
**Pull request by beeperdeeper089**
Resolves: #318
Authors:
@beeperdeeper089 

## Summary of changes
- Fix window scaling issue squashing aspect ratio of viewport.
  
## Caveats
Does this introduce any new bugs?
- None.

## On approval
Merge after testing from @tobyplowy

### CODE REVIEW

**Comment by tobyplowy** [comment]
Builds and runs. Scaling seems fixed.

**Comment by tobyplowy** [comment]
image
Phoenix mini edition :D

**Comment by beeperdeeper089** [comment]
Cool, if we get a review from Austin, this should be ready to merge.

**Review by apachano — APPROVED** [review]
LGTM

**Pull request merged**
