### PR TITLE
Fixed filesystem build issues.

### PR DESCRIPTION
**Pull request by M3TIOR**
Also added Beeper's credit where necessary. Please review the statement made in my commit log.

### CODE REVIEW

**Comment by M3TIOR** [comment]
Looks to be a c++11 issue

**Comment by M3TIOR** [comment]
https://stackoverflow.com/questions/33149878/experimentalfilesystem-linker-error

So useing `std::experimental::filesystem` is (most likely) impossible without the pre-existing build flag `-lstdc++fs` based on that source information. I have no way of testing this theory without pushing the changes upstream. Would someone else mind cloning my changes and making sure things build on your machine as well? It builds on mine. I need to fine a system that this doesn't build on for testing purposes. That or I could just keep shoving shit into Travis and have it complain all night.

**Comment by M3TIOR** [comment]
But ironically since we're using C++17 standard in our code, we shouldn't be needing to use the `std::experimental:filesystem` at all.

**Comment by apachano** [comment]
It compiles fine on my computer as well. The problem is OSX didn't add support for std::filesystem until 10.15 (Released this most recent November?) so in order to support OSX that isn't this up to date we need the experimental if compiled on a machine without the std::filesystem support. That being said my 2014 mac mini was eligible for the 10.15 upgrade so maybe we just tell people to upgrade and get over it? @beeperdeeper089 What we are trying to do should be possible but it is worth it?

**Pull request merged**
