### PR TITLE
Release 0.2

### PR DESCRIPTION
**Pull request by apachano**

### CODE REVIEW

**Comment by tobyplowy** [comment]
Builds and runs!

**Review by beeperdeeper089 — DISMISSED** [review]

**Comment by tobyplowy** [comment]
https://github.com/GentenStudios/Phoenix/issues/342

**Comment by tobyplowy** [comment]
https://github.com/GentenStudios/Phoenix/pull/343 Skybox fix.

**Comment by tobyplowy** [comment]
Still seems to crash on opening escape menu @apachano Wasn't this fixed like 2 or so PRs back?

**Review by beeperdeeper089 — APPROVED** [review]

**Review by tobyplowy — APPROVED** [review]
Splendid. Let's get this thing going! (Works as intended)

**Pull request merged**
