### PR TITLE
Cleaned up the rawEcho function and renamed it.

### PR DESCRIPTION
**Pull request by M3TIOR**
I started to work on making the actual commander more efficient but it will be fine for now. We can always clean that up later as well.

### CODE REVIEW

**Comment by beeperdeeper089** [comment]
Get it merging and it should be fine.

**Comment by M3TIOR** [comment]
Sorry that took forever I've been a bit overwhelmed lately. Need to relax my social appearently.

**Comment by apachano** [comment]
@M3TIOR I started work on a new branch to avoid cleaning up merge conflicts and lost code after the refactor (Sorry dropped the ball notifying you here). Would you mind applying these changes to feat-command so you can get credit for the work and we can merge easily?

**Comment by M3TIOR** [comment]
sure, or you could just add me as a code contributor at the command line.

**Comment by apachano** [comment]
No clue how to do that :/ still trying to google

**Comment by M3TIOR** [comment]
It's fine, I just took care of it for you in the new PR I made. But just for future refference, It's actually a github feature. Basically you just add as many `Co-authored-by: name <name@example.com>` instances as you need to the bottom of your commit message.

https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors

**Comment by apachano** [comment]
@M3TIOR I appreciate it, I will remember that for the future.

**Pull request closed without merging**
