### PR TITLE
Feat templates

### PR DESCRIPTION
**Pull request by apachano**
Addresses: none
Authors:
@apachano 

## Summary of changes
- Add new PR template
- Update file naming to match the rest of the repo
- Fix checkboxes in story template
- Change Bug Report template to use headers instead of bold text
  
## Caveats
None

## On approval
Please merge

### CODE REVIEW

**Comment by apachano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GentenStudios/Phoenix/pullRequest?prid=4787870&bid=15943546)

**Comment by apachano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 12
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GentenStudios/Phoenix/pullRequest?prid=4787870&bid=15943546)

**Comment by apachano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 11
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GentenStudios/Phoenix/pullRequest?prid=4787870&bid=15943546)

**Comment by apachano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GentenStudios/Phoenix/pullRequest?prid=4787870&bid=15943546)

**Comment by beeperdeeper089** [comment]
I won't merge it yet to see what we want to do about codacy because that is not passing

**Comment by apachano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GentenStudios/Phoenix/pullRequest?prid=4787870&bid=15943546)

**Comment by apachano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 18
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/GentenStudios/Phoenix/pullRequest?prid=4787870&bid=15943546)

**Pull request merged**
