### PR TITLE
Block Models

### PR DESCRIPTION
**Pull request by beeperdeeper089**
Resolves: #
Authors:
@beeperdeeper089 

## Summary of changes
- Add block models
- Render block models
- Let block models be selected in lua.
  
## Caveats
Does this introduce any new bugs?
- Still needs the new texturer to be implemented, but this can be merged first.

## On approval
Wait for me, need some testing.

### CODE REVIEW

**Comment by beeperdeeper089** [comment]
So, for texture order, the basic xpanel should only be using 4 textures, @tobyplowy if you could document in what order they appear (i cannot be arsed to figure this out) (for reference, normal blocks are done as north east south west top bottom).

And for ``XPanelCube``, there should be a maximum of 10 textures, 4 for the normal xpanel and another 6 for the cube.

Currently, you can use 1 texture for everything or the max (4 for normal xpanel, 10 for xpanelcube) but no fancy combos or anything, I'll implement this later when we do materials, etc...

**Comment by tobyplowy** [comment]
Tried to make a build. It failed.

**Comment by tobyplowy** [comment]
First issue I found so far is culling. 
image
image
Stairs cull blocks and blocks cull stairs in the wrong places. (Only the back and bottom side should do culling (But the culling on stairs is not mandatory for now if it's too hard to add properly))

For the xpanel I can't seem to test that seeing as I can't get the textures to work properly. 
When I add 4 textures I get a crash 
image
(What I did to get this)
```xpanel = {}
xpanel.name = "Test XPanel"
xpanel.id = "core.test_xpanel"
xpanel.model = "XPanel"
xpanel.textures = {"Assets/one.png", "Assets/two.png",
"Assets/three.png", "Assets/four.png"}
voxel.block.register(xpanel)```

**Comment by tobyplowy** [comment]
Then to test I also did the below \/ and that worked (Did not crash the game) but it did however only use the first texture (One.png)
```xpanel = {}
xpanel.name = "Test XPanel"
xpanel.id = "core.test_xpanel"
xpanel.model = "XPanel"
xpanel.textures = {"Assets/one.png", "Assets/two.png",
"Assets/three.png", "Assets/four.png",
"Assets/grass_top.png",  "Assets/dirt.png"}
voxel.block.register(xpanel)
```

**Comment by tobyplowy** [comment]
Tried to add the XPanel with block and prob gave the wrong name. This crashes the game. 
```
xpanblock = {}
xpanblock.name = "Test xpanblock"
xpanblock.id = "core.xpanblock"
xpanblock.model = "XPanelwithblock"
xpanblock.textures = {"Assets/one.png", "Assets/two.png",
"Assets/three.png", "Assets/four.png",
"Assets/grass_top.png",  "Assets/dirt.png"}
voxel.block.register(xpanblock)
```

**Comment by tobyplowy** [comment]
XPanelCube has the same problem as normal Xpan. The texture amount does not matter it will only use the first texture.

**Comment by beeperdeeper089** [comment]
Thanks, will take a look

**Comment by beeperdeeper089** [comment]
@tobyplowy Can I get a re-test on this. Thanks :)

**Comment by tobyplowy** [comment]
Problems solved. 
Builds as intended. 
+1

**Comment by tobyplowy** [comment]
Wait actually no. It's still broken I forgot to test some things.
Placing the Xpannel that included into the PR lua side crashes the game with a runtime error. (No onfo o the error window)
image
Here's the console output in case that's of any use.
[console output.txt](https://github.com/GentenStudios/Phoenix/files/5322444/console.output.txt)

The panels code is
```
xpanel = {}
xpanel.name = "Test XPanel"
xpanel.id = "core.test_xpanel"
xpanel.model = "XPanel"
xpanel.textures= {"Assets/xpanel.png"}
voxel.block.register(xpanel)
```
It's not the model tho. It's the code in general. If I copy the stair bloc code and change the model and name it's all fine. 
Maybe a little typo somewhere? (You may wanna fix that Lua typo before committing)

Ok yeah this does work just fine.
```
testPan = {}
testPan.name = "Test Xpan"
testPan.id = "core.testpan"
testPan.model = "XPanel"
testPan.textures= {"Assets/xpan_1.png"}
voxel.block.register(testPan)
```

Also trying to add 4 textures to the xpanel does this. (Crash with this message)
image

But adding 6 textures is fine... But only one will actually be used. (It's xpan_1.png)

```
testPan = {}
testPan.name = "Test Xpan"
testPan.id = "core.testpan"
testPan.model = "XPanel"
testPan.textures= {"Assets/xpan_1.png", "Assets/xpan_2.png",
"Assets/xpan_3.png", "Assets/xpan_4.png",
"Assets/grass_top.png",  "Assets/dirt.png"}
voxel.block.register(testPan)
```

**Comment by tobyplowy** [comment]
Everything past https://github.com/GentenStudios/Phoenix/pull/285/commits/aa2c3b3d5f60766c073ee89d3aa472c0a46472bf builds fine but keeps giving the below Lua errors.
```
[FATAL] D:\phoenixbuildfolder\source\Phoenix\Phoenix\Client\Source\Audio\Audio.cpp:170 [AUDIO] An unexpected (but recoverable) error occurred while loading: Modules/mod1/Assets/Audio/dirt_place.mp3
[FATAL] D:\phoenixbuildfolder\source\Phoenix\Phoenix\Common\Source\CMS\ModManager.cpp:48 [MODDING] An unexpected Lua error has occured. The application will now be aborted.
```
Getting rid of the audio files and removing the Lua code for them fixes the sound issue but still give s the 
`[FATAL] D:\phoenixbuildfolder\source\Phoenix\Phoenix\Common\Source\CMS\ModManager.cpp:48 [MODDING] An unexpected Lua error has occured. The application will now be aborted.`

**Comment by beeperdeeper089** [comment]
What the actual fuck

**Comment by tobyplowy** [comment]
IKR XD

**Pull request closed without merging**
