### PR TITLE
Feat main seperation

### PR DESCRIPTION
**Pull request by JosiahWI**
Move the Phoenix class and associated logic from Main.cpp into Client.cpp.

### CODE REVIEW

**Comment by JosiahWI** [comment]
It was not clear that you wanted the game loop in Client.cpp, I will fix that. I actually had it in there and then copied it back out. :man_facepalming: As for the headers: very good point. I had them all in there because I didn't know what I would need, and forgot to refactor it. I'll implement these changes. :+1:

**Comment by tobyplowy** [comment]
When you are ready please request a new review from Austin.

**Comment by apachano** [comment]
@beeperdeeper089 Should weigh in on this one. You deleted main.cpp and created a new file instead of moving and re-naming main.cpp to client.cpp

This will cause extensive extra work for the branches that change main.cpp (namely feat-chunk-management) since git won't recognize the new file on merge (and likely will try to restore main.cpp). It may be more efficient to reverse the changes and execute them in a way that git will recognize that the source file moved.

**Comment by beeperdeeper089** [comment]
Yeah, that is a good shout.

What might be useful, is just to redo this, but do ``git mv source destination`` and that will make git understand that it is a rename and not a delete/create event. This would be best otherwise we are going to have to many merge conflicts, other than that this is all fine.

**Comment by beeperdeeper089** [comment]
There's some wierd stuff going on with Git here, it thinks you made the documentation changes????

I'm not sure what the issue here is, if you know feel free to fix it but usually I find just copying your changes into another branch works quicker.

**Comment by SuperFola** [comment]
I thought the whole PR was about PR, it isn't?! What have I done

**Comment by beeperdeeper089** [comment]
No worries, Git is just being stupid.

I did these documentation updates in another branch and just merged them into develop today so I'm assuming either Github/Git is high af right now...

**Comment by beeperdeeper089** [comment]
Ping @JosiahWI, do you have an ETA for this? Otherwise I might need to comandeer this to get it done.

**Comment by beeperdeeper089** [comment]
I'm closing this since I've already implemented this in my layer stack branch - it was a QoL thing and was a pain to work with without doing it since this wasn't progressing too quickly. (no worries though, it was just some low hanging fruit.)

**Pull request closed without merging**
